### ISSUE TITLE
Documentation about how to run on CherryPy is outdated

### ISSUE THREAD

**Issue by csfulop** [pecan/pecan#103]
The Pecan documentation about how to run on CherryPy is outdated: https://pecan.readthedocs.io/en/latest/deployment.html#cherrypy
WSGI server was refactored out into cheroot project. See: https://github.com/cherrypy/cherrypy/issues/1585

**Comment by zzxwill** [comment]
I'm just curious why you are still interested in pecan? Seems it's dead already:(

**Comment by bertjwregeer** [comment]
Why would someone not be interested in `pecan`?

**Comment by csfulop** [comment]
> @csfulop May I know why you are still interested in `pecan`?

@zzxwill At work we still use it. I guess it was active when they started to use it...

**Comment by ryanpetrello** [comment]
👋

Pecan doesn't have a constant stream of activity because it has accomplished what @cleverdevil, @markmcclain, @alfredodeza, and I sought to make when we created it almost a decade ago:  a lean, easy-to-use Python web framework that gives you what you need to write a web service.

There are other great alternatives in the Python ecosystem that accomplish the same thing (like Flask, Pylons, and Falcon, to name a few).

Pecan is stable software that a group of maintainers periodically update as new versions of Python (or dependencies like WebOb) are released, and it doesn't have many bells and whistles beyond that.  That's a feature, not a bug.

**Comment by cleverdevil** [comment]
Well said @ryanpetrello. Stable software is a **good thing**. I still use Pecan regularly in very modern applications, including to build out AWS Lambda functions. Pecan is stable, fast, and fun to use.
