### ISSUE TITLE
Can't instantiate RootController(SecureController) and unlock a deeply nested controller

### ISSUE THREAD

**Issue by jdandrea** [pecan/pecan#52]
Given an API hierarchy of:

```
  root (RootController)
    v1 (V1Controller)
      project_id (ProjectController)
        things (ThingController)
          thing_id (ThingItemController)
        otherthings (OtherThingController)
          otherthing_id (OtherThingItemController)
```

... we want all endpoints in **ThingController** and **ThingItemController** to not require any AuthN/AuthZ checks. Everything else is to require AuthN/AuthZ.

Put another way, all endpoints in **ThingController** and **ThingItemController** would not be expected to ever return a 401 status. The other controllers/endpoints may return a 401 if AuthN/AuthZ fails. The URLs for which a 401 would never be returned look like this:

```
  http://hostname:8000/v1/project_id/things/
  http://hostname:8000/v1/project_id/things/thing_id/
```

What I discovered was that, if I make **RootController** a subclass of **SecureController**, unlocking **ThingController** and **ThingItemController** has no effect. They remain secured.

If, instead, I do not use **SecureController** at all, but instead decorate every individual endpoint I wish to secure with @secure, leaving the endpoints within **ThingController** and **ThingItemController** alone, everything works just fine.

I tried making a minimal test case to illustrate this. See http://paste.openstack.org/show/493873/ for two sets of example controllers. Each presumes AuthN/AuthZ fails by default.

The first set uses **SecureController** at the root level, instantiating **ThingController** and **ThingItemController**  using `unlocked()`. Accessing the URLs referenced above results in a 401 status, despite the unlocking.

The second set does not use **SecureController**. Instead, it decorates all endpoints in all controller classes (except for those in **ThingController** and **ThingItemController**) with @secure. Accessing only the URLs referenced above results in a 200 status.

Is this working as designed? Am I doing something fundamentally wrong in the **SecureController** case? Is there a bug?

If there's a simpler way to provide steps to reproduce, please advise. The controller hierarchy is particular to this problem, and this was the simplest way I could find to illustrate it. Thank you!

**Comment by ryanpetrello** [comment]
This isn't really a bug, but a limitation in ``SecureController`` that needs to be documented.

When using ``SecureController``, Pecan enforces **very** strict security on all class-encompassed code, which is re-checked at *every* URL path segment boundary.  In the following example:

    class LookupController(object):
        def __init__(self, id):
            # Potentially sensitive code could run here
            pass

        @unlocked
        @expose()
        def foo(self):
            return 'Testing 1 2 3'

    class RootController(SecureController):
        @expose()
        def _lookup(self, id, *remainder):
            # Potentially sensitive code could run here
            return LookupController(id), remainder

If a request were made to ``/12345/foo/``, there's code in the ``_lookup`` method *and* ``LookupController.__init__`` that will run *before* the route to ``foo`` can be discovered.  If you were to place an @unlocked on the ``_lookup`` function, all would be well.

Because of this, pecan doesn't really support @unlocked or @secure notations beyond a single layer of controller nesting - because of Pecan's dynamic object-dispatch style routing, it would be nearly impossible to assure sensitive code paths weren't reached; ``SecureController`` is really more useful for sectioning off large swaths of URL paths as restricted (think, e.g., ``/admin/``).

You could probably come up with a sneaky way to accomplish what you want with ``SecureController``, but it's likely to be pretty confusing.  If your use case is as simple as the example you've provided (an app that's unauthorized by default, with a handful of minor exceptions sprinkled here and there), you may consider just rolling something simple yourself using a hook (https://pecan.readthedocs.org/en/latest/hooks.html?highlight=hooks), e.g.,

    class V1Controller():
        @unlocked
        @expose()
        def foo(self):
            return "Hello, World!"

    class RootController(object):
        @expose()
        def index(self):
            return "Unreachable!"

        v1 = V1Controller()

    class PrivateHook(PecanHook):
        def before(self, state):
            if state.controller._pecan.get('secured', True):
                abort(401)

    app = TestApp(make_app(RootController(), hooks=[PrivateHook()]))
    assert app.get('/', expect_errors=True).status_int == 401
    assert app.get('/v1/foo/').status_int == 200

**Comment by jdandrea** [comment]
That helps a lot. Thank you!
