### ISSUE TITLE
Pecan fails to serve more than one concurrent request

### ISSUE THREAD

**Issue by ashishjain14** [pecan/pecan#84]
Details of Environment:
1) Eventlet based wsgi server
2) Pecan for wsgi application

When I try to push more than one request to my application I see only the first request passes through rest all fails with the error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pecan/middleware/recursive.py", line 56, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 843, in __call__
    del state.request
AttributeError: request

I have tested eventlet with a dummy app(non-pecan) and i am able to serve hundreds of request.

**Comment by ashishjain14** [comment]
Further debugging suggests that this is happening while returning the response back, So that means
pecan is able to accept multiple requests, back-end doing the required work and than while sending the response back there seems to be some problem.

**Comment by ryanpetrello** [comment]
Can you provide some more info on the code you're running, and how you're running it?  I created an example pecan project to test this, and wasn't able to reproduce the same issues:

    $ pecan create evented rest-api && cd evented
    $ pip install -e .
    $ cat serve.py

    import sys

    from eventlet import wsgi
    import eventlet
    from pecan import deploy

    wsgi.server(eventlet.listen(('', 8080)), deploy.deploy(sys.argv[1]))

If you want to use the thread-local ``pecan.request`` and ``pecan.response`` helpers with eventlet, you'll need to adjust your configuration.  You may wish to forego the use of these explicitly:

http://pecan.readthedocs.io/en/latest/contextlocals.html#disabling-thread-local-proxies

You can also try switching to the use of coroutine locals, (based on the error you're seeing, I expect that this is your actual issue):

    from eventlet.corolocal import local

    return make_app(
        app_conf.pop('root'),
        # ...
        context_local_factory=local,
        **app_conf
    )

**Comment by ashishjain14** [comment]
Thanks a lot for your prompt response on this, making the changes as suggested by you "switching to the use of coroutine locals" helps and I no longer see this issue. Can you please give little more information on what was the actual issue. is it one thread trying to modify another thread?

**Comment by ryanpetrello** [comment]
It's hard to say for sure without knowing how your code works, but based on your error, it sounded like an issue identifying the "current thread".  A common deployment approach for WSGI apps (like pecan) is a multi-threaded model where a pool of threads handle individual requests.  Pecan's ``pecan.request`` and ``pecan.response`` work using a feature of Python's threading library, [threading.local](https://docs.python.org/2/library/threading.html#threading.local); on each request, pecan creates a ``threading.local`` object to keep track of attributes of the request for that specific thread.  At the end of the request, the storage is emptied (so it's ready for the next request).

Eventlet is different - in an Eventlet WSGI server, each request is managed by a "greenlet", so there's no notion of a "current thread for the request".  A common solution to this problem is to use Eventlet's monkey-patching feature to automatically replaces Python's native ``threading.local`` with Eventlet's version - ``eventlet.corolocal.local`` - which works for greenlets, :

    from gevent import monkey
    monkey.patch_all() 

Monkey-patching with Eventlet, however, is a complicated, sensitive process.  It's possible to monkey-patch the wrong things - or too late, after the things you're trying to monkey-patch have already been imported.  Because of this, a nicer solution (that doesn't involve monkey-patching) is to just instruct pecan to use ``eventlet.corolocal.local`` **instead** of ``threading.local`` for managing the "current request state" (which is what the example I've provided does).
